### ISSUE TITLE
Backend crash

### ISSUE THREAD

**Issue by martincho222** [JuanErnestoVillegas/Restaurante-Buon-Appetito-Backend-Final#4]
Buenas chicos, como estan? estoy corrigiendo su proyecto, estoy viendo que el backend se rompe cuando registras un usuario y cuando intentas loguear un usuario recien creado.

![imagen](https://user-images.githubusercontent.com/57008725/181872147-e8001ddf-9749-4d89-a23e-08349f48259c.png)

**Comment by JuanErnestoVillegas** [comment]
Buenas noches, corregí el problema. Solucionado
